[package]
name = "routed_stake"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
royalty_pool = { git = "https://github.com/misofm/royalty-pool.git", rev = "2a55f9d8d47c8011ada5c74d181c807167d78da3" }
